### ISSUE TITLE
Sk6812 LED strips

### ISSUE THREAD

**Issue by haarhohe** [Vinz68/NeoPixel-Stair#2]
Vincent,

I am new to Arduino and in the process of adding the LED strips to my stairs. I was curious if your sketch would work for the above mentioned LED's that has the 4th color. Or what should I change so that the sketch does work? Thanks

**Comment by Vinz68** [comment]
Hello Haarhohe, 
This sketch uses the Adafruit Neopixel library for controlling single-wire-based LED pixels and strip.
I checked the [datasheet ](https://cdn-shop.adafruit.com/product-files/1138/SK6812+LED+datasheet+.pdf) of the SK6812 and the detail of the mentioned library (available on github).  
I used the a WS2812 ledstrip and I did read that this has the same brightness, color and protocol as the  SK6812-based LEDs. 
So this should work (but I have never tested it). Best thing would be to connect just a few leds (lets say 12) and configure the script as three ledstrips (LEDSTRIPS   3) , with 4 leds each (LEDSPERSTRIP  4) and test it. 
I would love to know if you succeed. Good luck !
