### ISSUE TITLE
Brightness of leds

### ISSUE THREAD

**Issue by Yns80** [Vinz68/NeoPixel-Stair#4]
Hi,

I found your sketch and i'm building my stair led with your code. Is there a way to control the brightness of the leds.

Thnx

**Comment by Vinz68** [comment]
Hello Yns80,
The brightnes can be controlled. Look at the code on line 92 or so, and you will see:

`strip.setBrightness(35);  // Adjust brightness here `  

Raising or lowering this value will change the brightness.

Good luck with it.

If you use the sketch then please mark with star so others can find it more easily. Thanks.

**Comment by Vinz68** [comment]
Hey, I updated the code (and comments). The brightness can be set in the configuration part (~line 32), here:

#define BRIGHTNESS      35        // Adjust brightness of the leds here

Higher value is brighter, lower value lowers the brightness.
Good luck with it Yns80 ; if you need any help plz. let me know.
Best regards, Vincent.

**Comment by Yns80** [comment]
Hi Vinz68,

Great thnx for the reply, i'm kinda a newbie on coding stuff. One more question ! If you have the spare time. How did you connect to strips on the stairs to each other, did you use continous data line like snake pattern or a zigzag patern to connect the data lines. During my small scall test i noticed the stairs always light up from the opposite side of each other for example the first step start from the left and second from the right. This happends using the snake patern connection used for the data lines i gues.

Thnx again for the reply and have a great day.

Cheers

**Comment by Vinz68** [comment]
I am not sure what you mean with snake versus zigzag ; but I have used it like this:
[Connection Details](https://content.instructables.com/ORIG/FOD/XLFY/IGTY8XVX/FODXLFYIGTY8XVX.png?auto=webp&frame=1&fit=bounds&md=e0c5a610a4fb2ea89a45d56e3d678e9a)

I hope that this images helps. 
Is it snake or zigzag pattern ?  ... just curious :)
