### ISSUE TITLE
Ldr

### ISSUE THREAD

**Issue by ash-1976** [Vinz68/NeoPixel-Stair#5]
Hi I wonder if you could help. When I upload code I get nothing working. I don't have an ldr attached do I need to change anything. Thanks

**Comment by Vinz68** [comment]
Hello ash-1976,
If you do not have a LDR, the only thing you need to change is the variable useLDR. In the script it has value true, you should set it to false ; like this:

bool useLDR = false;   

Hope this helps. Good luck.

If this helps you then please give this script a star , so others can find it more easily.  Thanks.

**Comment by ash-1976** [comment]
Hi thanks for getting back to me. I have done this but still nothing. I was originally using snikogos code    on instuctables which works fine apart from I have more led per step so when it turns each step on it doesn't work correctly but can't figure out how to change it from 35 to 41 per step. Thanks

**Comment by Vinz68** [comment]
Okay, did you check the connection details  link in the description ? That gives a nice picture for the wiring (from same guy you mentioned). Make sure the ground of the big powersupply is on ground of arduino as well.

Could be several other reasons why it does not work yet for you. But I am convinst you can get it to work; maybe these tips will help you:
1) Are your Passive Infra Red sensors working properly (PIR on pin 10 and 11). Maybe check them first if they work.
Here is a great article: https://learn.adafruit.com/pir-passive-infrared-proximity-motion-sensor/using-a-pir-w-arduino

2) Maybe your leds needs more brightness. There is a setting, you could raise it to say 100. to see if this helps
#define BRIGHTNESS      35     
3) The neopixels needs external power supply ; how more leds you have , how bigger the power supply. How many leds do you have in total and what is your external power supply (volts / ampere) ? Its my experience that most of the time this power supply is the problem...

If you checked all this (and still not working) then let me know ; it must be possible to help you further.
Good luck !
